const fs = require('fs');
const path = require('path');
const { parse } = require('csv-parse/sync');

// Read the CSV file
const csvFilePath = path.join(__dirname, '../src/data/worldcities.csv');
const fileContent = fs.readFileSync(csvFilePath, 'utf-8');

// Parse the CSV content
const records = parse(fileContent, {
  columns: true,
  skip_empty_lines: true,
  trim: true,
  skip_records_with_error: true
});

// Process the data into our desired format
const countriesMap = new Map();

records.forEach(record => {
  const countryName = record.country;
  const countryCode = record.iso2 || '';
  const stateName = record.admin_name || 'N/A';
  const cityName = record.city;
  
  // Skip if missing required fields
  if (!countryName || !cityName) return;
  
  // Initialize country if not exists
  if (!countriesMap.has(countryCode)) {
    countriesMap.set(countryCode, {
      name: countryName,
      code: countryCode,
      currency: getCurrencyForCountry(countryCode),
      currencySymbol: getCurrencySymbol(countryCode),
      states: new Map()
    });
  }
  
  const country = countriesMap.get(countryCode);
  
  // Initialize state if not exists
  if (!country.states.has(stateName)) {
    country.states.set(stateName, {
      name: stateName,
      cities: []
    });
  }
  
  // Add city to state
  const state = country.states.get(stateName);
  state.cities.push({ name: cityName });
});

// Convert maps to arrays for the final output
const countries = Array.from(countriesMap.values()).map(country => ({
  name: country.name,
  code: country.code,
  currency: country.currency,
  currencySymbol: country.currencySymbol,
  states: Array.from(country.states.values()).map(state => ({
    name: state.name,
    cities: state.cities
  }))
}));

// Generate the TypeScript file content
const fileContentTS = `// This file is auto-generated by scripts/processLocations.js
// Last updated: ${new Date().toISOString()}

interface City {
  name: string;
}

interface StateRegion {
  name: string;
  cities: City[];
}

export interface Country {
  name: string;
  code: string;
  states: StateRegion[];
  currency: string;
  currencySymbol: string;
}

// Comprehensive list of countries with their states and major cities
export const countries: Country[] = ${JSON.stringify(countries, null, 2)};

// Helper functions
export const getCountries = (): string[] => {
  return countries.map(country => country.name);
};

export const getStatesByCountry = (countryName: string): string[] => {
  const country = countries.find(c => c.name === countryName);
  return country ? country.states.map(state => state.name) : [];
};

export const getCitiesByState = (countryName: string, stateName: string): string[] => {
  const country = countries.find(c => c.name === countryName);
  if (!country) return [];
  
  const state = country.states.find(s => s.name === stateName);
  return state ? state.cities.map(city => city.name) : [];
};

export const getCurrencyForCountry = (countryName: string): string => {
  const country = countries.find(c => c.name === countryName);
  return country ? country.currency : 'USD';
};

// Helper function to get currency name from code
export const getCurrencyName = (code: string): string => {
  const currencyMap: Record<string, string> = {
    'USD': 'US Dollar',
    'EUR': 'Euro',
    'GBP': 'British Pound',
    'NGN': 'Nigerian Naira',
    'CAD': 'Canadian Dollar',
    'AUD': 'Australian Dollar',
    'JPY': 'Japanese Yen',
    'CNY': 'Chinese Yuan',
    'INR': 'Indian Rupee',
    'BRL': 'Brazilian Real',
    'ZAR': 'South African Rand',
    'KES': 'Kenyan Shilling',
    'GHS': 'Ghanaian Cedi',
    'EGP': 'Egyptian Pound',
    'MAD': 'Moroccan Dirham',
    'AED': 'UAE Dirham',
    'SAR': 'Saudi Riyal',
    'RUB': 'Russian Ruble',
    'TRY': 'Turkish Lira',
    'KRW': 'South Korean Won'
  };
  return currencyMap[code] || code;
};
`;

// Write the output to a new file
const outputPath = path.join(__dirname, '../src/data/enhancedLocations.ts');
fs.writeFileSync(outputPath, fileContentTS);

console.log(`✅ Successfully generated ${outputPath} with ${countries.length} countries`);

// Helper functions
function getCurrencyForCountry(countryCode) {
  const currencyMap = {
    'US': 'USD',
    'GB': 'GBP',
    'NG': 'NGN',
    'CA': 'CAD',
    'AU': 'AUD',
    'JP': 'JPY',
    'CN': 'CNY',
    'IN': 'INR',
    'BR': 'BRL',
    'ZA': 'ZAR',
    'KE': 'KES',
    'GH': 'GHS',
    'EG': 'EGP',
    'MA': 'MAD',
    'AE': 'AED',
    'SA': 'SAR',
    'RU': 'RUB',
    'TR': 'TRY',
    'KR': 'KRW'
  };
  
  return currencyMap[countryCode] || 'USD';
}

function getCurrencySymbol(currencyCode) {
  const symbolMap = {
    'USD': '$',
    'EUR': '€',
    'GBP': '£',
    'NGN': '₦',
    'CAD': 'C$',
    'AUD': 'A$',
    'JPY': '¥',
    'CNY': '¥',
    'INR': '₹',
    'BRL': 'R$',
    'ZAR': 'R',
    'KES': 'KSh',
    'GHS': 'GH₵',
    'EGP': 'E£',
    'MAD': 'DH',
    'AED': 'د.إ',
    'SAR': '﷼',
    'RUB': '₽',
    'TRY': '₺',
    'KRW': '₩'
  };
  
  return symbolMap[currencyCode] || '$';
}
