// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debugging: This will show in the Browser Console (F12)
console.log("🔍 Checking Supabase URL:", supabaseUrl); 
console.log("🔍 Checking Supabase Key prefix:", supabaseAnonKey?.substring(0, 20) + "...");

// Validate environment variables
if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Missing Supabase environment variables!');
  console.error('📝 Expected environment variables:');
  console.error('   VITE_SUPABASE_URL=your_supabase_url');
  console.error('   VITE_SUPABASE_ANON_KEY=your_supabase_anon_key');
  console.error('🔧 Check GitHub Actions secrets if this is production');
  
  // In production, show user-friendly error
  if (typeof window !== 'undefined' && window.location.hostname === 'filmloca.com') {
    const root = document.getElementById('root');
    if (root) {
      root.innerHTML = `
        <div style="padding: 40px; text-align: center; font-family: Arial, sans-serif;">
          <h2 style="color: #ff6b6b;">🔧 FilmLoca Configuration Required</h2>
          <p style="color: #666; margin: 20px 0;">
            The application is missing required configuration.
          </p>
          <div style="margin: 20px 0; padding: 20px; background: #f8f9fa; border-radius: 8px;">
            <p style="margin: 0; color: #495057;">
              Please check the browser console (F12) for technical details.
            </p>
          </div>
        </div>
      `;
    }
  }
  
  throw new Error('Supabase configuration is required. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

// Check for hardcoded placeholder values
if (supabaseUrl === "your_supabase_project_url" || supabaseAnonKey === "your_supabase_anon_key") {
  throw new Error("Hardcoded placeholder detected! VITE_SUPABASE_URL is not properly configured. Check your GitHub Secrets.");
}

// Validate URL format
try {
  new URL(supabaseUrl);
} catch (e) {
  console.error('❌ Invalid Supabase URL format:', supabaseUrl);
  throw new Error(`Invalid Supabase URL: ${supabaseUrl}. Must be a valid HTTP or HTTPS URL.`);
}

// Log configuration (without exposing the full key)
if (typeof window !== 'undefined') {
  console.log('🔧 Supabase Configuration:', {
    url: supabaseUrl,
    keyPrefix: supabaseAnonKey.substring(0, 20) + '...',
    usingEnvVars: !!import.meta.env.VITE_SUPABASE_URL
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});