// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || supabaseUrl === "your_supabase_project_url") {
  throw new Error("VITE_SUPABASE_URL is not defined! Check your GitHub Secrets.");
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);